scholarship_rates = [
    ("Üsküdar Üniversitesi", 25),
    ("Alanya Üniversitesi", 20),
    ("Altınbaş Üniversitesi", 25),
    ("Ankara Bilim Üniversitesi", 10),
    ("Ankara Medipol Üniversitesi", 25),
    ("Antalya Belek Üniversitesi", 15),
    ("Ataşehir Adıgüzel Meslek Yüksekokulu", 20),
    ("Avrasya Üniversitesi", 10),
    ("Avrupa Meslek Yüksekokulu", 25),
    ("Demiroğlu Bilim Üniversitesi", 10),
    ("Doğuş Üniversitesi", 25),
    ("FSM Vakıf Üniversitesi", 20),
    ("Fenerbahçe Üniversitesi", 20),
    ("Işık Üniversitesi", 60),
    ("İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu", 25),
    ("İzmir Kavram Meslek Yüksekokulu", 10),
    ("29 Mayıs Üniversitesi", 20),
    ("İstanbul Esenyurt Üniversitesi", 25),
    ("İstanbul Gedik Üniversitesi", 20),
    ("İstanbul Gelişim Üniversitesi", 10),
    ("İstanbul Kent Üniversitesi", 40),
    ("İstanbul Kültür Üniversitesi", 25),
    ("İstanbul Medipol Üniversitesi", 40),
    ("İstanbul Okan Üniversitesi", 25),
    ("İstanbul Rumeli Üniversitesi", 50),
    ("İstanbul Sabahattin Zaim Üniversitesi", 20),
    ("İstanbul Şişli Meslek Yüksekokulu", 5),
    ("İstanbul Ticaret Üniversitesi", 10),
    ("İstanbul Topkapı Üniversitesi", 60),
    ("İstanbul Yeniyüzyıl Üniversitesi", 5),
    ("İstinye Üniversitesi", 15),
    ("İzmir Ekonomi Üniversitesi", 25),
    ("İzmir Tınaztepe Üniversitesi", 15),
    ("Kocaeli Sağlık ve Teknoloji Üniversitesi", 25),
    ("Konya Gıda ve Tarım Üniversitesi", 45),
    ("KTO Karatay Üniversitesi", 30),
    ("Maltepe Üniversitesi", 50),
    ("MEF Üniversitesi", 25),
    ("Mudanya Üniversitesi", 10),
    ("Özyeğin Üniversitesi", 25),
    ("Piri Reis Üniversitesi", 20)
]

# List of universities to scrape
universities = [
    "Biruni Üniversitesi",
    "İstanbul Arel Üniversitesi",
    "İstanbul Atlas Üniversitesi",
    "İstanbul Aydın Üniversitesi",
    "İstanbul Bilgi Üniversitesi",
    "Kadir Has Üniversitesi",
    "Kapadokya Üniversitesi",
    "Kıbrıs Batı Üniversitesi",
    "Koç Üniversitesi",
    "Toros Üniversitesi",
    "Türk Hava Kurumu Üniversitesi",
    "Ufuk Üniversitesi",
    "Beykent Üniversitesi",
    "Beykoz Üniversitesi",
    "BezmiAlem Üniversitesi",
    "İstanbul Esenyurt Üniversitesi",
    "İstanbul Gedik Üniversitesi",
    "İstanbul Gelişim Üniversitesi",
    "İstanbul Kent Üniversitesi",
    "İstanbul Kültür Üniversitesi",
    "İstanbul Medipol Üniversitesi",
    "İstanbul Sabahattin Zaim Üniversitesi",
    "İstanbul Yeni Yüzyıl Üniversitesi",
    "İstinye Üniversitesi",
    "İzmir Tınaztepe Üniversitesi",
    "İstanbul Okan Üniversitesi",
    "İstanbul Topkapı Üniversitesi",
    "İstanbul Şişli Meslek Yüksekokulu",
    "İstanbul Rumeli Üniversitesi",
    "Çağ Üniversitesi",
    "Çankaya Üniversitesi",
    "Demiroğlu Bilim Üniversitesi",
    "Doğuş Üniversitesi",
    "Fatih Sultan Mehmet Vakıf Üniversitesi",
    "Fenerbahçe Üniversitesi",
    "Haliç Üniversitesi",
    "Hasan Kalyoncu Üniversitesi",
    "Işık Üniversitesi",
    "İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu",
    "İstanbul Sağlık ve Teknoloji Üniversitesi",
    "İzmir Kavram Meslek Yüksekokulu",
    "İbn Haldun Üniversitesi",
    "İhsan Doğramacı Bilkent Üniversitesi",
    "İstanbul 29 Mayıs Üniversitesi",
    "Nişantaşı Üniversitesi",
    "Yaşar Üniversitesi",
    "Yeditepe Üniversitesi",
    "Yüksek İhtisas Üniversitesi",
    "İzmir Ekonomi Üniversitesi",
    "İstanbul Ticaret Üniversitesi",
    "Kocaeli Sağlık ve Teknoloji Üniversitesi",
    "Konya Gıda Ve Tarım Üniversitesi",
    "KTO Karatay Üniversitesi",
    "Lokman Hekim Üniversitesi",
    "Maltepe Üniversitesi",
    "MEF Üniversitesi",
    "Mudanya Üniversitesi",
    "Nuh Naci Yazgan Üniversitesi",
    "Piri Reis Üniversitesi",
    "OSTİM Teknik Üniversitesi",
    "Özyeğin Üniversitesi",
    "SANKO Üniversitesi",
    "TOBB Ekonomi ve Teknoloji Üniversitesi",
    "Üsküdar Üniversitesi",
    "Acıbadem Üniversitesi",
    "Alanya Üniversitesi",
    "Altınbaş Üniversitesi",
    "Ankara Bilim Üniversitesi",
    "Ankara Medipol Üniversitesi",
    "Antalya Belek Üniversitesi",
    "Antalya Bilim Üniversitesi",
    "Ataşehir Adıgüzel Meslek Yüksekokulu",
    "Atılım Üniversitesi",
    "Avrasya Üniversitesi",
    "Bahçeşehir Kıbrıs Üniversitesi",
    "Başkent Üniversitesi"
]
